### ISSUE TITLE
Unable to run easy_feature_extraction.py

### ISSUE THREAD

**Issue by SiddGururani** [keunwoochoi/transfer_learning_music#1]
Hi,

I've been trying to get your feature extractor to work but I'm running into issues. First, the program requires 3 input arguments instead of 2, as mentioned in the README. The third input argument is for the number of workers to do the feature computation.

After I figured this out, I ran into this error:
```
Traceback (most recent call last):
  File "easy_feature_extraction.py", line 105, in <module>
    main(txt_path, out_path, n_jobs)
  File "easy_feature_extraction.py", line 76, in main
    all_features = predict_cpu(f_path, models, n_jobs)
  File "easy_feature_extraction.py", line 68, in predict_cpu
    features = pool.map(_predict_one, arg_gen)
  File "/usr/lib/python2.7/multiprocessing/pool.py", line 251, in map
    return self.map_async(func, iterable, chunksize).get()
  File "/usr/lib/python2.7/multiprocessing/pool.py", line 567, in get
    raise self._value
ValueError: CorrMM images and kernel must have the same stack size

Apply node that caused the error: CorrMM{half, (1, 1), (1, 1)}(Elemwise{Composite{maximum((i0 - i1), i2)}}[(0, 0)].0, Subtensor{::, ::, ::int64, ::int64}.0)
Toposort index: 51
Inputs types: [TensorType(float32, 4D), TensorType(float32, 4D)]
Inputs shapes: [(1, 1, 96, 1360), (3, 3, 32, 1)]
Inputs strides: [(384, 384, 4, 384), (4, 12, -36, -4)]
Inputs values: ['not shown', 'not shown']
Outputs clients: [[InplaceDimShuffle{0,2,3,1}(CorrMM{half, (1, 1), (1, 1)}.0)]]

Backtrace when the node is created(use Theano flag traceback.limit=N to make it longer):
  File "/usr/local/lib/python2.7/dist-packages/keras/engine/topology.py", line 572, in __call__
    self.add_inbound_node(inbound_layers, node_indices, tensor_indices)
  File "/usr/local/lib/python2.7/dist-packages/keras/engine/topology.py", line 635, in add_inbound_node
    Node.create_node(self, inbound_layers, node_indices, tensor_indices)
  File "/usr/local/lib/python2.7/dist-packages/keras/engine/topology.py", line 166, in create_node
    output_tensors = to_list(outbound_layer.call(input_tensors[0], mask=input_masks[0]))
  File "/usr/local/lib/python2.7/dist-packages/keras/models.py", line 386, in call
    return self.model.call(x, mask)
  File "/usr/local/lib/python2.7/dist-packages/keras/engine/topology.py", line 2247, in call
    output_tensors, output_masks, output_shapes = self.run_internal_graph(inputs, masks)
  File "/usr/local/lib/python2.7/dist-packages/keras/engine/topology.py", line 2390, in run_internal_graph
    computed_mask))
  File "/usr/local/lib/python2.7/dist-packages/keras/layers/convolutional.py", line 475, in call
    filter_shape=self.W_shape)
  File "/usr/local/lib/python2.7/dist-packages/keras/backend/theano_backend.py", line 1520, in conv2d
    filter_shape=filter_shape)

HINT: Use the Theano flag 'exception_verbosity=high' for a debugprint and storage map footprint of this apply node.
```

This appears to be some sort of problem that occurs due to a mismatch in the dimensions. Have you faced this before? It'd be awesome if you could advise me about how I should go about trying to get this to work!

Here is some info about the environment:
docker ubuntu 16.04 image
python 2.7
keras v1.2.2
theano 0.9.0
libav-tools installed for audio codecs, etc

**Comment by keunwoochoi** [comment]
Hi, about the arguments, yeah.. I'll fix it. Could you try to edit the code not to use multipreprocessing? I'm actually not sure what's wrong there.

**Comment by SiddGururani** [comment]
I figured out the problem. I looked at your audio tagging repo and noticed that the README there specifies that in keras.json 'image_dim_ordering' should be set to 'th'. I was using the theano backend but the image dimension ordering was still set to tensorflow.

Maybe you can add that instruction here as well. Code works perfectly now, good job!

**Comment by keunwoochoi** [comment]
Oh, right, I doubted it but thought it is already in `th` format. Thanks! I put in in readme just now.
