### ISSUE TITLE
ValueError: CorrMM images and kernel must have the same stack size

### ISSUE THREAD

**Issue by irisyupingren** [keunwoochoi/transfer_learning_music#4]
Full error:
Traceback (most recent call last):
  File "easy_feature_extraction.py", line 107, in <module>
    main(txt_path, out_path, 1)
  File "easy_feature_extraction.py", line 78, in main
    all_features = predict_cpu(f_path, models, n_jobs)
  File "easy_feature_extraction.py", line 70, in predict_cpu
    features = pool.map(_predict_one, arg_gen)
  File "/Users/irisren/anaconda/lib/python2.7/multiprocessing/pool.py", line 251, in map
    return self.map_async(func, iterable, chunksize).get()
  File "/Users/irisren/anaconda/lib/python2.7/multiprocessing/pool.py", line 567, in get
    raise self._value
ValueError: CorrMM images and kernel must have the same stack size

Any ideas why?

**Comment by baofff** [comment]
You can refer to issue #1

**Comment by irisyjohnson** [comment]
Thanks!
